#!/bin/sh /etc/rc.common

START=99
STOP=15

start() {
	/usr/bin/cqhttp -c /etc/cqhttp.yml -w /etc/cqhttp.d > /dev/null 2>&1 & echo "cqhttp is started"
}

stop() {
	killall cqhttp
	echo "cqhttp is stoped"
}

restart() {
	stop
	start
}
