#!/bin/sh /etc/rc.common

START=100
STOP=14

start() {
	cd /etc/little-paimon/LittlePaimon
	nb start > /dev/null 2>&1 & echo "LittlePaimon is started"
}

stop() {
	killall nb
	echo "LittlePaimon is stoped"
}

restart() {
	stop
	start
}
